#!/bin/sh

[ -f /usr/bin/lanplay-server-mgr ] || exit 0

start() {
	logger "Starting LANPLAY_SERVER_MGR services: "
	lanplay-server-mgr &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	logger "Shutting down LANPLAY_SERVER_MGR services: "
	kill -9 `pidof lanplay-server-mgr`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
